name: Setup Frontend

on:
  workflow_dispatch:  # Allows manual trigger from the Actions tab

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Or whatever version you need
    
    - name: Install frontend dependencies
      run: |
            pip install -r frontend/Requirements.txt
    
    - name: Run frontend (Streamlit)
      run: |
            streamlit run frontend/app_frontend.py
